// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeijcJIveOATgxhfJgVBV9uWXdMY-USQg',
    appId: '1:844855765448:web:35b045bedce4f766de78fd',
    messagingSenderId: '844855765448',
    projectId: 'toko-online4-a1498',
    authDomain: 'toko-online4-a1498.firebaseapp.com',
    storageBucket: 'toko-online4-a1498.firebasestorage.app',
    measurementId: 'G-N341TBJH6N',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeijcJIveOATgxhfJgVBV9uWXdMY-USQg',
    appId: '1:844855765448:web:35b045bedce4f766de78fd',
    messagingSenderId: '844855765448',
    projectId: 'toko-online4-a1498',
    authDomain: 'toko-online4-a1498.firebaseapp.com',
    storageBucket: 'toko-online4-a1498.firebasestorage.app',
    measurementId: 'G-N341TBJH6N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgVa4yHMacuSEKb2gzGfbbCMvQLpY2CQ0',
    appId: '1:844855765448:ios:6f6af5a238d02531de78fd',
    messagingSenderId: '844855765448',
    projectId: 'toko-online4-a1498',
    storageBucket: 'toko-online4-a1498.firebasestorage.app',
    iosBundleId: 'com.example.shoponline',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgVa4yHMacuSEKb2gzGfbbCMvQLpY2CQ0',
    appId: '1:844855765448:ios:6f6af5a238d02531de78fd',
    messagingSenderId: '844855765448',
    projectId: 'toko-online4-a1498',
    storageBucket: 'toko-online4-a1498.firebasestorage.app',
    iosBundleId: 'com.example.shoponline',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRtYhOMpVUlm7b_aFATL6wU0wAOGP7vlA',
    appId: '1:844855765448:android:f2cb1fbe1b22abb2de78fd',
    messagingSenderId: '844855765448',
    projectId: 'toko-online4-a1498',
    storageBucket: 'toko-online4-a1498.firebasestorage.app',
  );

}